version: '3'

tasks:
  build:
    desc: Build and scp into the cluster
    cmds:
    - pyinstaller mjobs/main.py --onefile --clean --name mjobs

  upload:
    desc: SCP to codon
    deps: [build]
    cmds:
    - scp dist/mjobs codon:~/
