name: Build mjobs Pyinstaller

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: rockylinux:8.5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Python
      run: |
        dnf module -y install python39
        python3 -m venv venv

    - name: Create bundle
      run: |
        source venv/bin/activate
        pip install -r requirements-dev.txt
        pyinstaller mjobs/main.py --onefile --clean --name mjobs

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: mjobs
        path: dist/mjobs
