name: Build mjobs Pyinstaller

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: rockylinux:8.5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create bundle
      run: |
        pip install -r requirements-dev.txt
        pyinstaller mjobs/main.py --onefile --clean --name mjobs

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: mjobs
        path: dist/mjobs
