name: Build mjobs Pyinstaller

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: rockylinux:8.5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    # - name: Setup Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'
    #     cache: pip

    - name: Create bundle
      run: |
        pip install -r requirements-dev.txt
        pyinstaller mjobs/main.py --onefile --clean --name mjobs

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: mjobs
        path: dist/mjobs
