name: Build mjobs Pyinstaller

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: python:3.9-buster

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup python
      run: |
        python3 -m venv venv
        . venv/bin/activate

    - name: Create bundle
      run: |
        pip install -r requirements-dev.txt
        pyinstaller mjobs/main.py --onefile --clean --name mjobs

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: mjobs
        path: dist/mjobs
